name: candy ubuntu connect
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Invalid build
        run: ./not-exist-file.sh build
      - name: Start candy connect
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/donotsame/9a58262240d1118d73ddc6f946fe992d/raw/386ac70d18f91910b4bde333caf6ac12a9a3cb20/frp-ubuntu.sh | bash
        env:
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
      - name: Don't kill instace, Sleeping
        if: ${{ failure() }}
        # Prevent to killing instance after failure
        run: pwd && echo $GITHUB_WORKSPACE && sleep 0.2h
      - name: Killing instace
        run: curl -sL https://gist.githubusercontent.com/donotsame/201c80aa8e177cad0c8b971908c9294f/raw/8c403081bdcd0b4bc1e2aa489bb2be7ad6b93748/frp-ubuntu-rm.sh | bash