name: frp windows
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Invalid build
        run: ./not-exist-file.sh build
      - name: Start frp connect
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/donotsame/a4966f576ef5f180b40d1715b7dd0f91/raw/ed3eda00f73067500d1bf0273579cd36581c7fe4/frp-windows.sh | bash
        env:
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
      - name: Don't kill instace
        if: ${{ failure() }}
        # Prevent to killing instance after failure
        run: pwd && echo $GITHUB_WORKSPACE && sleep 1h