name: frp ubuntu connect
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Invalid build
        run: ./not-exist-file.sh build
      - name: Start frp connect
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/donotsame/9a58262240d1118d73ddc6f946fe992d/raw/386ac70d18f91910b4bde333caf6ac12a9a3cb20/frp-ubuntu.sh | bash
        env:
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
      - name: Start candy connect
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/donotsame/a1d4e89aed1342b9e0301307c6672360/raw/b64cfc2d6813668d851c43401c7a41cd13d22292/candy-ubuntu.sh | bash
      - name: Don't kill instace, Sleeping
        if: ${{ failure() }}
        # Prevent to killing instance after failure
        run: pwd && echo $GITHUB_WORKSPACE && sleep 1h
      - name: Killing instace
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/donotsame/201c80aa8e177cad0c8b971908c9294f/raw/72c1d95b8c589c5e26330b99c076c39b96e32874/frp-ubuntu-rm.sh | bash